name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.11.06
  - xarray
  - hvplot
  - xhistogram
  - pandas
  - intake
  - intake-xarray
  - curl
  - seaborn
  - zarr
  - pip
  - pip:
    - sat-search
